obj-$(CONFIG_MALI400) += mali/
obj-$(CONFIG_ST_SOCINFO) += st-socinfo.o
obj-$(CONFIG_ST_CPUFREQ_INIT)	+= st_cpufreq_init.o
obj-$(CONFIG_ST_AMBA_BRIDGE)	+=st_amba_bridge.o
obj-$(CONFIG_STI_REBOOT_CAUSE)	+= reboot_reason.o